name: Build APK

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'  # Java 17에서 8로 변경

    # Android SDK 라이센스 자동 수락
    - name: Setup Android SDK Licenses
      run: |
        mkdir -p $ANDROID_HOME/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license

    # Android SDK 설정
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: latest

    # Gradle 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # APK 빌드
    - name: Build APK
      run: ./gradlew assembleRelease

    # APK 아티팩트 업로드
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
