name: Build APK

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1. Android SDK 설정을 위한 Java 17 설치
    - name: Set up JDK 17 for SDK setup
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # 2. Android SDK 라이센스 설정
    - name: Setup Android SDK Licenses
      run: |
        mkdir -p $ANDROID_HOME/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license

    # 3. Android SDK 설정
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: latest

    # 4. 필요한 Android SDK 패키지 설치
    - name: Install Android SDK packages
      run: |
        sdkmanager "platforms;android-31" "build-tools;33.0.2" "ndk;25.2.9519653"

    # 5. Gradle 빌드를 위한 Java 8 설치
    - name: Set up JDK 8 for Gradle build
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    # 6. Gradle 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 7. APK 빌드
    - name: Build APK
      run: ./gradlew assembleRelease

    # 8. APK 아티팩트 업로드
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
