name: Build APK

on:
  push:
    branches:
      - '**' # 모든 브랜치에 대해 트리거
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. Android SDK 설정
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3 # v2에서 v3로 업데이트
      
    # 4. Android SDK 라이센스 동의
    - name: Accept Android SDK licenses
      run: |
        echo "y" | sdkmanager --licenses
        
    # 5. Android SDK 패키지 설치
    - name: Install Android SDK packages
      run: |
        sdkmanager "platforms;android-31" "build-tools;33.0.2" "ndk;25.2.9519653"
      
    # 6. Gradle 캐싱 설정 (빌드 속도 향상)
    - name: Setup Gradle Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 7. Gradle 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # 8. APK 빌드
    - name: Build APK
      run: ./gradlew assembleRelease

    # 9. APK 아티팩트 업로드
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
